# Generated by Django 3.1.7 on 2021-07-24 18:44

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABOUT_CSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ADMISSION_PRO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CONTACT_US',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, null=True)),
                ('last_name', models.CharField(max_length=60, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='COURSES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=90, null=True)),
                ('content', djrichtextfield.models.RichTextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DAILY_EDITORI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=200)),
                ('Title', models.CharField(max_length=200, null=True)),
                ('pdf', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='DEMO_IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='FEE_STRUCTURES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(choices=[('PRELIMINARY_CUM_MAIN', 'prelimitary_cum_main'), ('OPTIONAL_PAPERS', 'optional_papers'), ('GENERAL_STUDIES', 'general_studies')], default='prelimitary_cum_main', max_length=30)),
                ('content', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HOME_ENQUIRY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('Course', models.CharField(max_length=60, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HOME_MEET_FACULTY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('state', models.CharField(max_length=60, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='INFOGRAPHICS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MGSTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NCERT_CATEGORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
                ('category_image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PGSTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PREVIOUS_PAPER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paper_Category', models.CharField(choices=[('UPSC Prelims Previous Year Question Papers', 'UPSC Prelims Previous Year Question Papers'), ('Essay Previous Year Question Papers', 'Essay Previous Year Question Papers'), ('UPSC Mains General Studies Previous Year Question Papers', 'UPSC Mains General Studies Previous Year Question Papers'), ('UPSC Mains Optional Subjects Previous Year Question Papers', 'UPSC Mains Optional Subjects Previous Year Question Papers')], max_length=100, null=True)),
                ('year', models.IntegerField(null=True)),
                ('name', models.TextField(blank=True, max_length=60, null=True)),
                ('paper1_name', models.TextField(blank=True, max_length=60, null=True)),
                ('paper2_name', models.TextField(blank=True, max_length=60, null=True)),
                ('paper1_pdf', models.FileField(max_length=60, null=True, upload_to='')),
                ('paper2_pdf', models.FileField(max_length=60, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SYLLABUSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.CreateModel(
            name='YOJANA_CATEGORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=60)),
                ('category_image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='YOJANA_PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=200)),
                ('Book_image', models.FileField(null=True, upload_to='')),
                ('Book_pdf', models.FileField(null=True, upload_to='')),
                ('book_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zias.yojana_category')),
            ],
        ),
        migrations.CreateModel(
            name='NCERT_BOOKS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=200)),
                ('Book_image', models.FileField(null=True, upload_to='')),
                ('Book_pdf', models.FileField(null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('book_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zias.ncert_category')),
            ],
        ),
    ]
