# Generated by Django 3.1.7 on 2021-07-26 00:49

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('zias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KURUKSHERTAA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', djrichtextfield.models.RichTextField(null=True)),
            ],
        ),
    ]
